name: Variables Printer

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'the name'
        required: true
        default: 'ajaydip'
  

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Print the input variables
        run: |
          echo "name: ${{ github.event.inputs.name }}"
    
