# This is a basic workflow to help you get started with Actions
name: Output context

# Event triggers
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'the name'
        required: true
        default: 'ajaydip'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # This step checks out the workflow repository so that the runner can access the content
      - name: Checkout
        uses: actions/checkout@v2
        
      # This step runs a shell command on the runner machine
      - name: Print the input variables
        run: |
          echo "name: ${{ github.event.inputs.name }}"
    
